name: Build and Publish via Docker Compose

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PrepareReg Names
        run: |

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image using Docker Compose
        run: |
          cd dockerfiles
          docker compose build 

      - name: Tag image
        run: |
          docker tag mc_rtc_tutorials ghcr.io/$IMAGE_REPOSITORY:latest
        env:
          IMAGE_REPOSITORY: $(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
